export const ROI_TIERS = [
  {
    key: 'roi_free',
    label: 'Identity Only',
    addOn: 0,
    addOnEUR: 0,
    description: 'Vehicle identity from ROI register',
    features: ['Make, model, year, colour', 'Engine size & fuel type', 'NCT status', 'First registration date'],
  },
  {
    key: 'roi_standard',
    label: 'Standard',
    addOn: 4.99,
    addOnEUR: 5.99,
    description: 'Identity + current market valuation + demand',
    features: ['Everything in Identity', 'Current market valuation', 'Market demand score', 'Days to sell estimate'],
  },
  {
    key: 'roi_pro',
    label: 'Pro',
    addOn: 12.99,
    addOnEUR: 15.99,
    description: 'Standard + future valuation + price guide',
    features: ['Everything in Standard', 'Future value projection', 'Market price guide', 'Depreciation forecast'],
  },
  {
    key: 'roi_history',
    label: 'History',
    addOn: 17.99,
    addOnEUR: 20.99,
    description: 'Pro + full Cartell vehicle history check',
    features: ['Everything in Pro', 'Full Cartell history', 'Outstanding finance', 'Ownership count'],
  },
];

export const IE_MENU = [
  {
    key: 'ie_valuation',
    label: 'Valuation',
    description: 'Trade and retail values for the Irish market',
    price: 2.99,
    priceEUR: 3.99,
    preSelected: true,
    locked: true,
    enabled: true,
  },
  {
    key: 'ie_nct',
    label: 'NCT History',
    description: 'NCT due date and test history',
    price: 0,
    priceEUR: 0,
    preSelected: true,
    locked: true,
    enabled: true,
  },
  {
    key: 'ie_service_history',
    label: 'Service History',
    description: 'OE digital service records where available',
    price: 5.00,
    priceEUR: 5.99,
    preSelected: false,
    locked: false,
    enabled: true,
  },
  {
    key: 'ie_history',
    label: 'Full History Check',
    description: 'Cartell — write-off, finance, mileage, stolen, tax, NCT detail',
    price: 15.00,
    priceEUR: 17.99,
    preSelected: false,
    locked: false,
    enabled: false,
  },
];

export const PRICING = {
  menu: [
    {
      key: 'valuation',
      label: 'Valuation',
      description: 'Trade, retail and private sale values',
      price: 1.99,
      preSelected: true,
      locked: true,
      enabled: true,
    },
    {
      key: 'writeoff',
      label: 'Write-off / Cat S/N Check',
      description: 'Insurance write-off category and history',
      price: 2.49,
      preSelected: false,
      locked: false,
      enabled: true,
    },
    {
      key: 'finance',
      label: 'Finance Check',
      description: 'Outstanding finance against the vehicle',
      price: 1.49,
      preSelected: false,
      locked: false,
      enabled: true,
    },
    {
      key: 'stolen',
      label: 'Stolen Check',
      description: 'Police stolen vehicle database check',
      price: 1.29,
      preSelected: false,
      locked: false,
      enabled: true,
    },
    {
      key: 'salvagehistory',
      label: 'Salvage History Check',
      description: 'See if this vehicle has been previously sold at a salvage auction — lot date, damage description, mileage, and photos from prior listings',
      price: 1.49,
      cost: 0.50,
      preSelected: false,
      locked: false,
      enabled: true,
    },
    {
      key: 'market_demand',
      label: 'Market Demand',
      description: 'How quickly this vehicle sells in the current market',
      price: 0.69,
      preSelected: false,
      locked: false,
      enabled: true,
    },
    {
      key: 'previous_adverts',
      label: 'Previous Adverts',
      description: 'Previous asking prices and listings for this vehicle',
      price: 0.79,
      preSelected: false,
      locked: false,
      enabled: true,
    },
    {
      key: 'mot',
      label: 'MOT History',
      description: 'Full MOT pass/fail history from DVSA',
      price: 0,
      preSelected: true,
      locked: true,
      enabled: true,
    },
    {
      key: 'mileage_detail',
      label: 'Mileage / Clocking Check',
      description: 'Full MOT mileage timeline with rollback detection (mi & km normalised). A free verdict shows on your lookup; this adds the detailed reading-by-reading timeline to your report.',
      price: 0.99,
      preSelected: false,
      locked: false,
      enabled: true,
    },
    {
      key: 'service_history',
      label: 'Service History',
      description: 'OE manufacturer service records where available',
      price: 3.49,
      preSelected: false,
      locked: false,
      enabled: true,
    },
    {
      key: 'owner_history',
      label: 'Owner / Keeper History',
      description: 'Number of previous keepers, each ownership-change date, and any previous registration plates (GB & NI).',
      price: 0.99,
      preSelected: false,
      locked: false,
      enabled: true,
    },
    {
      key: 'salvage_predictor',
      label: 'Salvage Bid Predictor',
      description: 'Predicted auction hammer price for salvage vehicles',
      price: 0.99,
      preSelected: false,
      locked: false,
      enabled: false,
    },
  ],
  salvageAssessment: {
    price: 8.99,
    priceEUR: 10.99, // EUR opt-in (ROI/IE lots only); GBP remains the default base
    enabled: true,
  },
}
